// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"realtime_quiz_system/internal/dao/internal"
)

// answerOptionsDao is the data access object for the table answer_options.
// You can define custom methods on it to extend its functionality as needed.
type answerOptionsDao struct {
	*internal.AnswerOptionsDao
}

var (
	// AnswerOptions is a globally accessible object for table answer_options operations.
	AnswerOptions = answerOptionsDao{internal.NewAnswerOptionsDao()}
)

// Add your custom methods and functionality below.
