// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"realtime_quiz_system/internal/dao/internal"
)

// leaderboardSnapshotsDao is the data access object for the table leaderboard_snapshots.
// You can define custom methods on it to extend its functionality as needed.
type leaderboardSnapshotsDao struct {
	*internal.LeaderboardSnapshotsDao
}

var (
	// LeaderboardSnapshots is a globally accessible object for table leaderboard_snapshots operations.
	LeaderboardSnapshots = leaderboardSnapshotsDao{internal.NewLeaderboardSnapshotsDao()}
)

// Add your custom methods and functionality below.
