// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"realtime_quiz_system/internal/dao/internal"
)

// questionsDao is the data access object for the table questions.
// You can define custom methods on it to extend its functionality as needed.
type questionsDao struct {
	*internal.QuestionsDao
}

var (
	// Questions is a globally accessible object for table questions operations.
	Questions = questionsDao{internal.NewQuestionsDao()}
)

// Add your custom methods and functionality below.
