// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"realtime_quiz_system/internal/dao/internal"
)

// quizSessionsDao is the data access object for the table quiz_sessions.
// You can define custom methods on it to extend its functionality as needed.
type quizSessionsDao struct {
	*internal.QuizSessionsDao
}

var (
	// QuizSessions is a globally accessible object for table quiz_sessions operations.
	QuizSessions = quizSessionsDao{internal.NewQuizSessionsDao()}
)

// Add your custom methods and functionality below.
