// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"realtime_quiz_system/internal/dao/internal"
)

// quizzesDao is the data access object for the table quizzes.
// You can define custom methods on it to extend its functionality as needed.
type quizzesDao struct {
	*internal.QuizzesDao
}

var (
	// Quizzes is a globally accessible object for table quizzes operations.
	Quizzes = quizzesDao{internal.NewQuizzesDao()}
)

// Add your custom methods and functionality below.
