// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"realtime_quiz_system/internal/dao/internal"
)

// sessionParticipantsDao is the data access object for the table session_participants.
// You can define custom methods on it to extend its functionality as needed.
type sessionParticipantsDao struct {
	*internal.SessionParticipantsDao
}

var (
	// SessionParticipants is a globally accessible object for table session_participants operations.
	SessionParticipants = sessionParticipantsDao{internal.NewSessionParticipantsDao()}
)

// Add your custom methods and functionality below.
