// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"realtime_quiz_system/internal/dao/internal"
)

// userAnswersDao is the data access object for the table user_answers.
// You can define custom methods on it to extend its functionality as needed.
type userAnswersDao struct {
	*internal.UserAnswersDao
}

var (
	// UserAnswers is a globally accessible object for table user_answers operations.
	UserAnswers = userAnswersDao{internal.NewUserAnswersDao()}
)

// Add your custom methods and functionality below.
